name: Deploy Workflow

on:
  push:
    branches:
      - "**"

jobs:
  build-and-test:
    name: Build and Test Kata
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0"

      - name: Restore NuGet Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --no-restore

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal
